// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: artical.proto

package articaldemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode    int64  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage string `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Resp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type CreateArticalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CreateArticalRequest) Reset() {
	*x = CreateArticalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticalRequest) ProtoMessage() {}

func (x *CreateArticalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticalRequest.ProtoReflect.Descriptor instead.
func (*CreateArticalRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticalRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateArticalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticalRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateArticalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CreateArticalResponse) Reset() {
	*x = CreateArticalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticalResponse) ProtoMessage() {}

func (x *CreateArticalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticalResponse.ProtoReflect.Descriptor instead.
func (*CreateArticalResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticalResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type Artical struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text   string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Artical) Reset() {
	*x = Artical{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artical) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artical) ProtoMessage() {}

func (x *Artical) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artical.ProtoReflect.Descriptor instead.
func (*Artical) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{3}
}

func (x *Artical) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Artical) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Artical) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artical) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type QueryArticalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []int32 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *QueryArticalRequest) Reset() {
	*x = QueryArticalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArticalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticalRequest) ProtoMessage() {}

func (x *QueryArticalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticalRequest.ProtoReflect.Descriptor instead.
func (*QueryArticalRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{4}
}

func (x *QueryArticalRequest) GetIDs() []int32 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type QueryArticalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp    *Resp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Artical []*Artical `protobuf:"bytes,2,rep,name=artical,proto3" json:"artical,omitempty"`
}

func (x *QueryArticalResponse) Reset() {
	*x = QueryArticalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArticalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticalResponse) ProtoMessage() {}

func (x *QueryArticalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticalResponse.ProtoReflect.Descriptor instead.
func (*QueryArticalResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{5}
}

func (x *QueryArticalResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryArticalResponse) GetArtical() []*Artical {
	if x != nil {
		return x.Artical
	}
	return nil
}

type CreateLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int32  `protobuf:"varint,2,opt,name=articalID,proto3" json:"articalID,omitempty"`
	Type      int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CreateLikeStarRequest) Reset() {
	*x = CreateLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeStarRequest) ProtoMessage() {}

func (x *CreateLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeStarRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateLikeStarRequest) GetArticalID() int32 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *CreateLikeStarRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CreateLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CreateLikeStarResponse) Reset() {
	*x = CreateLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeStarResponse) ProtoMessage() {}

func (x *CreateLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeStarResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type DeleteLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int32  `protobuf:"varint,2,opt,name=articalID,proto3" json:"articalID,omitempty"`
	Type      int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DeleteLikeStarRequest) Reset() {
	*x = DeleteLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeStarRequest) ProtoMessage() {}

func (x *DeleteLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeStarRequest.ProtoReflect.Descriptor instead.
func (*DeleteLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DeleteLikeStarRequest) GetArticalID() int32 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *DeleteLikeStarRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DeleteLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *DeleteLikeStarResponse) Reset() {
	*x = DeleteLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeStarResponse) ProtoMessage() {}

func (x *DeleteLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeStarResponse.ProtoReflect.Descriptor instead.
func (*DeleteLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type LikeStar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int64  `protobuf:"varint,2,opt,name=articalID,proto3" json:"articalID,omitempty"`
}

func (x *LikeStar) Reset() {
	*x = LikeStar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStar) ProtoMessage() {}

func (x *LikeStar) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStar.ProtoReflect.Descriptor instead.
func (*LikeStar) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{10}
}

func (x *LikeStar) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LikeStar) GetArticalID() int64 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

type QueryLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int32  `protobuf:"varint,2,opt,name=articalID,proto3" json:"articalID,omitempty"`
	Type      int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *QueryLikeStarRequest) Reset() {
	*x = QueryLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLikeStarRequest) ProtoMessage() {}

func (x *QueryLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLikeStarRequest.ProtoReflect.Descriptor instead.
func (*QueryLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{11}
}

func (x *QueryLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *QueryLikeStarRequest) GetArticalID() int32 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *QueryLikeStarRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type QueryLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp     *Resp     `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	LikeStar *LikeStar `protobuf:"bytes,2,opt,name=likeStar,proto3" json:"likeStar,omitempty"`
}

func (x *QueryLikeStarResponse) Reset() {
	*x = QueryLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLikeStarResponse) ProtoMessage() {}

func (x *QueryLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLikeStarResponse.ProtoReflect.Descriptor instead.
func (*QueryLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{12}
}

func (x *QueryLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryLikeStarResponse) GetLikeStar() *LikeStar {
	if x != nil {
		return x.LikeStar
	}
	return nil
}

type QueryAllLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Type     int32  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *QueryAllLikeStarRequest) Reset() {
	*x = QueryAllLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAllLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllLikeStarRequest) ProtoMessage() {}

func (x *QueryAllLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllLikeStarRequest.ProtoReflect.Descriptor instead.
func (*QueryAllLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{13}
}

func (x *QueryAllLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *QueryAllLikeStarRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type QueryAllLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp       *Resp    `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	ArticalIDs []uint32 `protobuf:"varint,2,rep,packed,name=articalIDs,proto3" json:"articalIDs,omitempty"`
}

func (x *QueryAllLikeStarResponse) Reset() {
	*x = QueryAllLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAllLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllLikeStarResponse) ProtoMessage() {}

func (x *QueryAllLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllLikeStarResponse.ProtoReflect.Descriptor instead.
func (*QueryAllLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{14}
}

func (x *QueryAllLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryAllLikeStarResponse) GetArticalIDs() []uint32 {
	if x != nil {
		return x.ArticalIDs
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ArticalID   int32  `protobuf:"varint,2,opt,name=articalID,proto3" json:"articalID,omitempty"`
	UserName    string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	CommentText string `protobuf:"bytes,4,opt,name=commentText,proto3" json:"commentText,omitempty"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{15}
}

func (x *Comment) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Comment) GetArticalID() int32 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *Comment) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Comment) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticalID   int32  `protobuf:"varint,1,opt,name=articalID,proto3" json:"articalID,omitempty"`
	UserName    string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	CommentText string `protobuf:"bytes,3,opt,name=commentText,proto3" json:"commentText,omitempty"`
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentRequest) GetArticalID() int32 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *CreateCommentRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type QueryCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentID []int32 `protobuf:"varint,1,rep,packed,name=commentID,proto3" json:"commentID,omitempty"`
}

func (x *QueryCommentRequest) Reset() {
	*x = QueryCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommentRequest) ProtoMessage() {}

func (x *QueryCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommentRequest.ProtoReflect.Descriptor instead.
func (*QueryCommentRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{18}
}

func (x *QueryCommentRequest) GetCommentID() []int32 {
	if x != nil {
		return x.CommentID
	}
	return nil
}

type QueryCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp    *Resp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Comment []*Comment `protobuf:"bytes,2,rep,name=comment,proto3" json:"comment,omitempty"`
}

func (x *QueryCommentResponse) Reset() {
	*x = QueryCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommentResponse) ProtoMessage() {}

func (x *QueryCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommentResponse.ProtoReflect.Descriptor instead.
func (*QueryCommentResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{19}
}

func (x *QueryCommentResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryCommentResponse) GetComment() []*Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentID int32 `protobuf:"varint,1,opt,name=commentID,proto3" json:"commentID,omitempty"`
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCommentRequest) GetCommentID() int32 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCommentResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

var File_artical_proto protoreflect.FileDescriptor

var file_artical_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x4c, 0x0a, 0x04,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x3e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x22, 0x5b, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x27, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x44, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x49, 0x44, 0x73, 0x22, 0x6d, 0x0a, 0x14, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x65, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x3f, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x22, 0x65, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x44, 0x0a, 0x08, 0x4c, 0x69, 0x6b,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x22,
	0x64, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x08,
	0x6c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x22, 0x49, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x4c,
	0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x49, 0x44, 0x73, 0x22, 0x75, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x72, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78,
	0x74, 0x22, 0x3e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x22, 0x33, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x6d, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32, 0xc3, 0x06, 0x0a, 0x0e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12,
	0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5b, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x12, 0x22, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x22,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x4c,
	0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x24, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x55, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x20, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65,
	0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_artical_proto_rawDescOnce sync.Once
	file_artical_proto_rawDescData = file_artical_proto_rawDesc
)

func file_artical_proto_rawDescGZIP() []byte {
	file_artical_proto_rawDescOnce.Do(func() {
		file_artical_proto_rawDescData = protoimpl.X.CompressGZIP(file_artical_proto_rawDescData)
	})
	return file_artical_proto_rawDescData
}

var file_artical_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_artical_proto_goTypes = []interface{}{
	(*Resp)(nil),                     // 0: articaldemo.Resp
	(*CreateArticalRequest)(nil),     // 1: articaldemo.CreateArticalRequest
	(*CreateArticalResponse)(nil),    // 2: articaldemo.CreateArticalResponse
	(*Artical)(nil),                  // 3: articaldemo.Artical
	(*QueryArticalRequest)(nil),      // 4: articaldemo.QueryArticalRequest
	(*QueryArticalResponse)(nil),     // 5: articaldemo.QueryArticalResponse
	(*CreateLikeStarRequest)(nil),    // 6: articaldemo.CreateLikeStarRequest
	(*CreateLikeStarResponse)(nil),   // 7: articaldemo.CreateLikeStarResponse
	(*DeleteLikeStarRequest)(nil),    // 8: articaldemo.DeleteLikeStarRequest
	(*DeleteLikeStarResponse)(nil),   // 9: articaldemo.DeleteLikeStarResponse
	(*LikeStar)(nil),                 // 10: articaldemo.LikeStar
	(*QueryLikeStarRequest)(nil),     // 11: articaldemo.QueryLikeStarRequest
	(*QueryLikeStarResponse)(nil),    // 12: articaldemo.QueryLikeStarResponse
	(*QueryAllLikeStarRequest)(nil),  // 13: articaldemo.QueryAllLikeStarRequest
	(*QueryAllLikeStarResponse)(nil), // 14: articaldemo.QueryAllLikeStarResponse
	(*Comment)(nil),                  // 15: articaldemo.Comment
	(*CreateCommentRequest)(nil),     // 16: articaldemo.CreateCommentRequest
	(*CreateCommentResponse)(nil),    // 17: articaldemo.CreateCommentResponse
	(*QueryCommentRequest)(nil),      // 18: articaldemo.QueryCommentRequest
	(*QueryCommentResponse)(nil),     // 19: articaldemo.QueryCommentResponse
	(*DeleteCommentRequest)(nil),     // 20: articaldemo.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),    // 21: articaldemo.DeleteCommentResponse
}
var file_artical_proto_depIdxs = []int32{
	0,  // 0: articaldemo.CreateArticalResponse.resp:type_name -> articaldemo.Resp
	0,  // 1: articaldemo.QueryArticalResponse.resp:type_name -> articaldemo.Resp
	3,  // 2: articaldemo.QueryArticalResponse.artical:type_name -> articaldemo.Artical
	0,  // 3: articaldemo.CreateLikeStarResponse.resp:type_name -> articaldemo.Resp
	0,  // 4: articaldemo.DeleteLikeStarResponse.resp:type_name -> articaldemo.Resp
	0,  // 5: articaldemo.QueryLikeStarResponse.resp:type_name -> articaldemo.Resp
	10, // 6: articaldemo.QueryLikeStarResponse.likeStar:type_name -> articaldemo.LikeStar
	0,  // 7: articaldemo.QueryAllLikeStarResponse.resp:type_name -> articaldemo.Resp
	0,  // 8: articaldemo.CreateCommentResponse.resp:type_name -> articaldemo.Resp
	0,  // 9: articaldemo.QueryCommentResponse.resp:type_name -> articaldemo.Resp
	15, // 10: articaldemo.QueryCommentResponse.comment:type_name -> articaldemo.Comment
	0,  // 11: articaldemo.DeleteCommentResponse.resp:type_name -> articaldemo.Resp
	1,  // 12: articaldemo.ArticalService.CreateArtical:input_type -> articaldemo.CreateArticalRequest
	4,  // 13: articaldemo.ArticalService.QueryArtical:input_type -> articaldemo.QueryArticalRequest
	6,  // 14: articaldemo.ArticalService.CreateLikeStar:input_type -> articaldemo.CreateLikeStarRequest
	8,  // 15: articaldemo.ArticalService.DeleteLikeStar:input_type -> articaldemo.DeleteLikeStarRequest
	11, // 16: articaldemo.ArticalService.QueryLikeStar:input_type -> articaldemo.QueryLikeStarRequest
	13, // 17: articaldemo.ArticalService.QueryAllLikeStar:input_type -> articaldemo.QueryAllLikeStarRequest
	16, // 18: articaldemo.ArticalService.CreateComment:input_type -> articaldemo.CreateCommentRequest
	18, // 19: articaldemo.ArticalService.QueryComment:input_type -> articaldemo.QueryCommentRequest
	20, // 20: articaldemo.ArticalService.DeleteComment:input_type -> articaldemo.DeleteCommentRequest
	2,  // 21: articaldemo.ArticalService.CreateArtical:output_type -> articaldemo.CreateArticalResponse
	5,  // 22: articaldemo.ArticalService.QueryArtical:output_type -> articaldemo.QueryArticalResponse
	7,  // 23: articaldemo.ArticalService.CreateLikeStar:output_type -> articaldemo.CreateLikeStarResponse
	9,  // 24: articaldemo.ArticalService.DeleteLikeStar:output_type -> articaldemo.DeleteLikeStarResponse
	12, // 25: articaldemo.ArticalService.QueryLikeStar:output_type -> articaldemo.QueryLikeStarResponse
	14, // 26: articaldemo.ArticalService.QueryAllLikeStar:output_type -> articaldemo.QueryAllLikeStarResponse
	17, // 27: articaldemo.ArticalService.CreateComment:output_type -> articaldemo.CreateCommentResponse
	19, // 28: articaldemo.ArticalService.QueryComment:output_type -> articaldemo.QueryCommentResponse
	21, // 29: articaldemo.ArticalService.DeleteComment:output_type -> articaldemo.DeleteCommentResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_artical_proto_init() }
func file_artical_proto_init() {
	if File_artical_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_artical_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artical); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArticalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArticalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeStar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAllLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAllLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artical_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artical_proto_goTypes,
		DependencyIndexes: file_artical_proto_depIdxs,
		MessageInfos:      file_artical_proto_msgTypes,
	}.Build()
	File_artical_proto = out.File
	file_artical_proto_rawDesc = nil
	file_artical_proto_goTypes = nil
	file_artical_proto_depIdxs = nil
}
