// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: artical.proto

package articaldemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticalServiceClient is the client API for ArticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticalServiceClient interface {
	CreateArtical(ctx context.Context, in *CreateArticalRequest, opts ...grpc.CallOption) (*CreateArticalResponse, error)
	QueryArtical(ctx context.Context, in *QueryArticalRequest, opts ...grpc.CallOption) (*QueryArticalResponse, error)
	CreateLikeStar(ctx context.Context, in *CreateLikeStarRequest, opts ...grpc.CallOption) (*CreateLikeStarResponse, error)
	DeleteLikeStar(ctx context.Context, in *DeleteLikeStarRequest, opts ...grpc.CallOption) (*DeleteLikeStarResponse, error)
	QueryLikeStar(ctx context.Context, in *QueryLikeStarRequest, opts ...grpc.CallOption) (*QueryLikeStarResponse, error)
	QueryAllLikeStar(ctx context.Context, in *QueryAllLikeStarRequest, opts ...grpc.CallOption) (*QueryAllLikeStarResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	QueryComment(ctx context.Context, in *QueryCommentRequest, opts ...grpc.CallOption) (*QueryCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type articalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticalServiceClient(cc grpc.ClientConnInterface) ArticalServiceClient {
	return &articalServiceClient{cc}
}

func (c *articalServiceClient) CreateArtical(ctx context.Context, in *CreateArticalRequest, opts ...grpc.CallOption) (*CreateArticalResponse, error) {
	out := new(CreateArticalResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/CreateArtical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) QueryArtical(ctx context.Context, in *QueryArticalRequest, opts ...grpc.CallOption) (*QueryArticalResponse, error) {
	out := new(QueryArticalResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/QueryArtical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) CreateLikeStar(ctx context.Context, in *CreateLikeStarRequest, opts ...grpc.CallOption) (*CreateLikeStarResponse, error) {
	out := new(CreateLikeStarResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/CreateLikeStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) DeleteLikeStar(ctx context.Context, in *DeleteLikeStarRequest, opts ...grpc.CallOption) (*DeleteLikeStarResponse, error) {
	out := new(DeleteLikeStarResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/DeleteLikeStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) QueryLikeStar(ctx context.Context, in *QueryLikeStarRequest, opts ...grpc.CallOption) (*QueryLikeStarResponse, error) {
	out := new(QueryLikeStarResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/QueryLikeStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) QueryAllLikeStar(ctx context.Context, in *QueryAllLikeStarRequest, opts ...grpc.CallOption) (*QueryAllLikeStarResponse, error) {
	out := new(QueryAllLikeStarResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/QueryAllLikeStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) QueryComment(ctx context.Context, in *QueryCommentRequest, opts ...grpc.CallOption) (*QueryCommentResponse, error) {
	out := new(QueryCommentResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/QueryComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articalServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/articaldemo.ArticalService/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticalServiceServer is the server API for ArticalService service.
// All implementations must embed UnimplementedArticalServiceServer
// for forward compatibility
type ArticalServiceServer interface {
	CreateArtical(context.Context, *CreateArticalRequest) (*CreateArticalResponse, error)
	QueryArtical(context.Context, *QueryArticalRequest) (*QueryArticalResponse, error)
	CreateLikeStar(context.Context, *CreateLikeStarRequest) (*CreateLikeStarResponse, error)
	DeleteLikeStar(context.Context, *DeleteLikeStarRequest) (*DeleteLikeStarResponse, error)
	QueryLikeStar(context.Context, *QueryLikeStarRequest) (*QueryLikeStarResponse, error)
	QueryAllLikeStar(context.Context, *QueryAllLikeStarRequest) (*QueryAllLikeStarResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	QueryComment(context.Context, *QueryCommentRequest) (*QueryCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedArticalServiceServer()
}

// UnimplementedArticalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticalServiceServer struct {
}

func (UnimplementedArticalServiceServer) CreateArtical(context.Context, *CreateArticalRequest) (*CreateArticalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArtical not implemented")
}
func (UnimplementedArticalServiceServer) QueryArtical(context.Context, *QueryArticalRequest) (*QueryArticalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArtical not implemented")
}
func (UnimplementedArticalServiceServer) CreateLikeStar(context.Context, *CreateLikeStarRequest) (*CreateLikeStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLikeStar not implemented")
}
func (UnimplementedArticalServiceServer) DeleteLikeStar(context.Context, *DeleteLikeStarRequest) (*DeleteLikeStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLikeStar not implemented")
}
func (UnimplementedArticalServiceServer) QueryLikeStar(context.Context, *QueryLikeStarRequest) (*QueryLikeStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLikeStar not implemented")
}
func (UnimplementedArticalServiceServer) QueryAllLikeStar(context.Context, *QueryAllLikeStarRequest) (*QueryAllLikeStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAllLikeStar not implemented")
}
func (UnimplementedArticalServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedArticalServiceServer) QueryComment(context.Context, *QueryCommentRequest) (*QueryCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryComment not implemented")
}
func (UnimplementedArticalServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedArticalServiceServer) mustEmbedUnimplementedArticalServiceServer() {}

// UnsafeArticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticalServiceServer will
// result in compilation errors.
type UnsafeArticalServiceServer interface {
	mustEmbedUnimplementedArticalServiceServer()
}

func RegisterArticalServiceServer(s grpc.ServiceRegistrar, srv ArticalServiceServer) {
	s.RegisterService(&ArticalService_ServiceDesc, srv)
}

func _ArticalService_CreateArtical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).CreateArtical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/CreateArtical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).CreateArtical(ctx, req.(*CreateArticalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_QueryArtical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArticalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).QueryArtical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/QueryArtical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).QueryArtical(ctx, req.(*QueryArticalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_CreateLikeStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).CreateLikeStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/CreateLikeStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).CreateLikeStar(ctx, req.(*CreateLikeStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_DeleteLikeStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLikeStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).DeleteLikeStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/DeleteLikeStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).DeleteLikeStar(ctx, req.(*DeleteLikeStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_QueryLikeStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLikeStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).QueryLikeStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/QueryLikeStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).QueryLikeStar(ctx, req.(*QueryLikeStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_QueryAllLikeStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLikeStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).QueryAllLikeStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/QueryAllLikeStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).QueryAllLikeStar(ctx, req.(*QueryAllLikeStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_QueryComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).QueryComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/QueryComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).QueryComment(ctx, req.(*QueryCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticalService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticalServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articaldemo.ArticalService/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticalServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticalService_ServiceDesc is the grpc.ServiceDesc for ArticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articaldemo.ArticalService",
	HandlerType: (*ArticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArtical",
			Handler:    _ArticalService_CreateArtical_Handler,
		},
		{
			MethodName: "QueryArtical",
			Handler:    _ArticalService_QueryArtical_Handler,
		},
		{
			MethodName: "CreateLikeStar",
			Handler:    _ArticalService_CreateLikeStar_Handler,
		},
		{
			MethodName: "DeleteLikeStar",
			Handler:    _ArticalService_DeleteLikeStar_Handler,
		},
		{
			MethodName: "QueryLikeStar",
			Handler:    _ArticalService_QueryLikeStar_Handler,
		},
		{
			MethodName: "QueryAllLikeStar",
			Handler:    _ArticalService_QueryAllLikeStar_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _ArticalService_CreateComment_Handler,
		},
		{
			MethodName: "QueryComment",
			Handler:    _ArticalService_QueryComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _ArticalService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artical.proto",
}
