// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: artical.proto

package articaldemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode    int64  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage string `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Resp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type CreateArticalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CreateArticalRequest) Reset() {
	*x = CreateArticalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticalRequest) ProtoMessage() {}

func (x *CreateArticalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticalRequest.ProtoReflect.Descriptor instead.
func (*CreateArticalRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticalRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateArticalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticalRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateArticalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CreateArticalResponse) Reset() {
	*x = CreateArticalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticalResponse) ProtoMessage() {}

func (x *CreateArticalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticalResponse.ProtoReflect.Descriptor instead.
func (*CreateArticalResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticalResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type Artical struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text   string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Artical) Reset() {
	*x = Artical{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artical) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artical) ProtoMessage() {}

func (x *Artical) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artical.ProtoReflect.Descriptor instead.
func (*Artical) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{3}
}

func (x *Artical) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Artical) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Artical) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artical) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type QueryArticalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *QueryArticalRequest) Reset() {
	*x = QueryArticalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArticalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticalRequest) ProtoMessage() {}

func (x *QueryArticalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticalRequest.ProtoReflect.Descriptor instead.
func (*QueryArticalRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{4}
}

func (x *QueryArticalRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type QueryArticalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp    *Resp    `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Artical *Artical `protobuf:"bytes,2,opt,name=artical,proto3" json:"artical,omitempty"`
}

func (x *QueryArticalResponse) Reset() {
	*x = QueryArticalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArticalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticalResponse) ProtoMessage() {}

func (x *QueryArticalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticalResponse.ProtoReflect.Descriptor instead.
func (*QueryArticalResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{5}
}

func (x *QueryArticalResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryArticalResponse) GetArtical() *Artical {
	if x != nil {
		return x.Artical
	}
	return nil
}

type CreateLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int64  `protobuf:"varint,2,opt,name=ArticalID,proto3" json:"ArticalID,omitempty"`
	Type      int64  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *CreateLikeStarRequest) Reset() {
	*x = CreateLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeStarRequest) ProtoMessage() {}

func (x *CreateLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeStarRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateLikeStarRequest) GetArticalID() int64 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *CreateLikeStarRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CreateLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CreateLikeStarResponse) Reset() {
	*x = CreateLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeStarResponse) ProtoMessage() {}

func (x *CreateLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeStarResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type DeleteLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int64  `protobuf:"varint,2,opt,name=ArticalID,proto3" json:"ArticalID,omitempty"`
	Type      int64  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *DeleteLikeStarRequest) Reset() {
	*x = DeleteLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeStarRequest) ProtoMessage() {}

func (x *DeleteLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeStarRequest.ProtoReflect.Descriptor instead.
func (*DeleteLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DeleteLikeStarRequest) GetArticalID() int64 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *DeleteLikeStarRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DeleteLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *DeleteLikeStarResponse) Reset() {
	*x = DeleteLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeStarResponse) ProtoMessage() {}

func (x *DeleteLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeStarResponse.ProtoReflect.Descriptor instead.
func (*DeleteLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type LikeStar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int64  `protobuf:"varint,2,opt,name=ArticalID,proto3" json:"ArticalID,omitempty"`
}

func (x *LikeStar) Reset() {
	*x = LikeStar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStar) ProtoMessage() {}

func (x *LikeStar) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStar.ProtoReflect.Descriptor instead.
func (*LikeStar) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{10}
}

func (x *LikeStar) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LikeStar) GetArticalID() int64 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

type QueryLikeStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ArticalID int64  `protobuf:"varint,2,opt,name=ArticalID,proto3" json:"ArticalID,omitempty"`
	Type      int64  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *QueryLikeStarRequest) Reset() {
	*x = QueryLikeStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLikeStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLikeStarRequest) ProtoMessage() {}

func (x *QueryLikeStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLikeStarRequest.ProtoReflect.Descriptor instead.
func (*QueryLikeStarRequest) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{11}
}

func (x *QueryLikeStarRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *QueryLikeStarRequest) GetArticalID() int64 {
	if x != nil {
		return x.ArticalID
	}
	return 0
}

func (x *QueryLikeStarRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type QueryLikeStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp     *Resp     `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	LikeStar *LikeStar `protobuf:"bytes,2,opt,name=LikeStar,proto3" json:"LikeStar,omitempty"`
}

func (x *QueryLikeStarResponse) Reset() {
	*x = QueryLikeStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artical_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLikeStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLikeStarResponse) ProtoMessage() {}

func (x *QueryLikeStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artical_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLikeStarResponse.ProtoReflect.Descriptor instead.
func (*QueryLikeStarResponse) Descriptor() ([]byte, []int) {
	return file_artical_proto_rawDescGZIP(), []int{12}
}

func (x *QueryLikeStarResponse) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryLikeStarResponse) GetLikeStar() *LikeStar {
	if x != nil {
		return x.LikeStar
	}
	return nil
}

var File_artical_proto protoreflect.FileDescriptor

var file_artical_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x4c, 0x0a, 0x04,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x3e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x22, 0x5b, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x25, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x6d, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x07,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x65, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22,
	0x65, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x44, 0x0a, 0x08, 0x4c, 0x69, 0x6b, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x22, 0x64, 0x0a,
	0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x08, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x08, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x32, 0xd5, 0x03, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x22, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x22, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6b, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_artical_proto_rawDescOnce sync.Once
	file_artical_proto_rawDescData = file_artical_proto_rawDesc
)

func file_artical_proto_rawDescGZIP() []byte {
	file_artical_proto_rawDescOnce.Do(func() {
		file_artical_proto_rawDescData = protoimpl.X.CompressGZIP(file_artical_proto_rawDescData)
	})
	return file_artical_proto_rawDescData
}

var file_artical_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_artical_proto_goTypes = []interface{}{
	(*Resp)(nil),                   // 0: articaldemo.Resp
	(*CreateArticalRequest)(nil),   // 1: articaldemo.CreateArticalRequest
	(*CreateArticalResponse)(nil),  // 2: articaldemo.CreateArticalResponse
	(*Artical)(nil),                // 3: articaldemo.Artical
	(*QueryArticalRequest)(nil),    // 4: articaldemo.QueryArticalRequest
	(*QueryArticalResponse)(nil),   // 5: articaldemo.QueryArticalResponse
	(*CreateLikeStarRequest)(nil),  // 6: articaldemo.CreateLikeStarRequest
	(*CreateLikeStarResponse)(nil), // 7: articaldemo.CreateLikeStarResponse
	(*DeleteLikeStarRequest)(nil),  // 8: articaldemo.DeleteLikeStarRequest
	(*DeleteLikeStarResponse)(nil), // 9: articaldemo.DeleteLikeStarResponse
	(*LikeStar)(nil),               // 10: articaldemo.LikeStar
	(*QueryLikeStarRequest)(nil),   // 11: articaldemo.QueryLikeStarRequest
	(*QueryLikeStarResponse)(nil),  // 12: articaldemo.QueryLikeStarResponse
}
var file_artical_proto_depIdxs = []int32{
	0,  // 0: articaldemo.CreateArticalResponse.resp:type_name -> articaldemo.Resp
	0,  // 1: articaldemo.QueryArticalResponse.resp:type_name -> articaldemo.Resp
	3,  // 2: articaldemo.QueryArticalResponse.artical:type_name -> articaldemo.Artical
	0,  // 3: articaldemo.CreateLikeStarResponse.resp:type_name -> articaldemo.Resp
	0,  // 4: articaldemo.DeleteLikeStarResponse.resp:type_name -> articaldemo.Resp
	0,  // 5: articaldemo.QueryLikeStarResponse.resp:type_name -> articaldemo.Resp
	10, // 6: articaldemo.QueryLikeStarResponse.LikeStar:type_name -> articaldemo.LikeStar
	1,  // 7: articaldemo.ArticalService.CreateArtical:input_type -> articaldemo.CreateArticalRequest
	4,  // 8: articaldemo.ArticalService.QueryArtical:input_type -> articaldemo.QueryArticalRequest
	6,  // 9: articaldemo.ArticalService.CreateLikeStar:input_type -> articaldemo.CreateLikeStarRequest
	8,  // 10: articaldemo.ArticalService.DeleteLikeStar:input_type -> articaldemo.DeleteLikeStarRequest
	11, // 11: articaldemo.ArticalService.QueryLikeStar:input_type -> articaldemo.QueryLikeStarRequest
	2,  // 12: articaldemo.ArticalService.CreateArtical:output_type -> articaldemo.CreateArticalResponse
	5,  // 13: articaldemo.ArticalService.QueryArtical:output_type -> articaldemo.QueryArticalResponse
	7,  // 14: articaldemo.ArticalService.CreateLikeStar:output_type -> articaldemo.CreateLikeStarResponse
	9,  // 15: articaldemo.ArticalService.DeleteLikeStar:output_type -> articaldemo.DeleteLikeStarResponse
	12, // 16: articaldemo.ArticalService.QueryLikeStar:output_type -> articaldemo.QueryLikeStarResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_artical_proto_init() }
func file_artical_proto_init() {
	if File_artical_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_artical_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artical); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArticalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArticalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeStar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLikeStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artical_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLikeStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artical_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artical_proto_goTypes,
		DependencyIndexes: file_artical_proto_depIdxs,
		MessageInfos:      file_artical_proto_msgTypes,
	}.Build()
	File_artical_proto = out.File
	file_artical_proto_rawDesc = nil
	file_artical_proto_goTypes = nil
	file_artical_proto_depIdxs = nil
}
